apiVersion: v1
kind: Service
metadata:
  name: catfacts-service
  labels:
    app: catfacts
    name: catfacts
spec:
  type: NodePort
  ports:
    - targetPort: 7777
      port: 7777
      nodePort: 30777
  selector:
    app: catfacts