name: Terraform create GKE defualt cluster

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.6"

      - name: Initialize Terraform
        run: terraform init

      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Apply Terraform changes
        run: terraform apply -auto-approve ./terraform/create_gcp_kubernetes_cluster.tf
