name: Terraform create GKE defualt cluster

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'install gke-gcloud-auth-plugin'
        run: 'gcloud components install gke-gcloud-auth-plugin'

      - name: 'set project'
        run: 'gcloud config set project catfacts-384312'

      - name: 'set zone'
        run: 'gcloud config set compute/zone europe-west1'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.6"

      - name: Initialize Terraform
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform init

      - name: Check terraform state file exists
        id: check_cluster_online
        run: if [[ -z $(gsutil -q stat gs://catfacts_terraform_state_file/terraform.tfstate) ]] ; then echo "cluster_online=true" >> "$GITHUB_OUTPUT"; else echo "cluster_online=false" >> "$GITHUB_OUTPUT" ; fi

      - name: test2
        id: test22222
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: echo "${{ steps.check_cluster_online.outputs.cluster_online }}"

      - name: get bucket terraform state file
        id: download_tfstate_file_from_gcloud_storage
        if: steps.check_cluster_online.outputs.cluster_online == 'true'
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: gcloud storage cp --continue-on-error gs://catfacts_terraform_state_file/terraform.tfstate terraform.tfstate

      - name: Plan Terraform
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform plan -input=false -var 'GOOGLE_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}'

      - name: Apply Terraform changes - Creating GKE cluster
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform apply -auto-approve -input=false -var 'GOOGLE_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}'

      - name: test
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: 'ls -la'

      - name: upload terraform file to bucket
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: gcloud storage cp --continue-on-error terraform.tfstate gs://catfacts_terraform_state_file/
