name: Terraform create GKE defualt cluster

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.6"

      - name: Initialize Terraform
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform init

      - name: Export Google creds as env var
        run: export TF_VAR_GOOGLE_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}

      - name: Plan Terraform
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform plan -input=false

      - name: Apply Terraform changes - Creating GKE cluster
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform apply -auto-approve -input=false
        
