name: Terraform create GKE defualt cluster

on:
  workflow_dispatch:

jobs:
  apply:
    runs-on: ubuntu-latest
    outputs:
      catfacts_cluster_online: ${{ steps.check_cluster_online.outputs.catfacts_cluster_online_status }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'install gke-gcloud-auth-plugin'
        run: 'gcloud components install gke-gcloud-auth-plugin'

      - name: 'set project'
        run: 'gcloud config set project catfacts-384312'

      - name: 'set zone'
        run: 'gcloud config set compute/zone europe-west1'

      - name: 'check if cluster already exists'
        id: check_cluster_online
        run: 'if [[ -z $(gcloud container clusters list --filter NAME=catfacts) ]]; echo "catfacts_cluster_online_status=false" >> $GITHUB_OUTPUT; fi'

      - name: Set up Terraform
        if: needs.apply.outputs.catfacts_cluster_online_status == 'false'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.0.6"

      - name: Initialize Terraform
        if: needs.apply.outputs.catfacts_cluster_online_status == 'false'
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform init

      - name: Plan Terraform
        if: needs.apply.outputs.catfacts_cluster_online_status == 'false'
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform plan -input=false -var 'GOOGLE_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}'

      - name: Apply Terraform changes - Creating GKE cluster
        if: needs.apply.outputs.catfacts_cluster_online_status == 'false'
        working-directory: terraform/create_gcp_kubernetes_cluster
        run: terraform apply -auto-approve -input=false -var 'GOOGLE_CREDENTIALS=${{ secrets.GCP_CREDENTIALS }}'
        
