name: Terraform Deploy CatFacts Kubernetes Deployment

on:
  workflow_dispatch:

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'install gke-gcloud-auth-plugin'
        run: 'gcloud components install gke-gcloud-auth-plugin'

      - name: 'set project'
        run: 'gcloud config set project catfacts-384312'

      - name: 'set zone'
        run: 'gcloud config set compute/zone europe-west1'

      - name: 'set kubernetes context'
        run: 'gcloud container clusters get-credentials catfacts --zone europe-west1'

      - name: 'test1'
        run: 'ls -laR'

      - name: 'test2'
        run: 'cat *.json'

      - name: 'deploy catfacts deployment'
        run: 'kubectl apply -f kubernetes_deployments/catfacts_deployment.yaml'

      - name: 'deploy catfacts service'
        run: 'kubectl apply -f kubernetes_services/catfacts_service.yaml'
        
